version: '3'

services:

  ### APP (PHP-FPM + CADDY) ##############################################
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app_local
    build:
      args:
        - PHP_VERSION=7.4
        - PHP_FPM_INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - PHP_FPM_INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
      context: .
      dockerfile: docker/app/Dockerfile_local
    image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest # образ, который строим. НЕ ТОТ из которого строимся
    volumes:
      - ./:/var/www:cached
    ports:
      - "80:8080"
      - "127.0.0.1:3000:3000"
    expose:
      - "9000"

  ### SSL proxy (Caddy Server) #########################################
#  ssl:
#    image: registry.gitlab.com/flagstudio/laraflag:ssl-base
#    ports:
#      - "443:443"
#      - "80:80"
#    volumes:
#      - ./docker/ssl/Caddyfile_SSL:/etc/Caddyfile


  ### PostgreSQL ###########################################
  postgres:
    image: postgres:13-alpine
    command: postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data:delegated
    ports:
      - "127.0.0.1:5432:5432"
